export const provincesVietNam = [
  'An Giang',
  'Bac Giang',
  'Bac Kan',
  'Bac Lieu',
  'Bac Ninh',
  'Ba Ria-Vung Tau',
  'Ben Tre',
  'Binh Dinh',
  'Binh Duong',
  'Binh Phuoc',
  'Binh Thuan',
  'Ca Mau',
  'Cao Bang',
  'Dac Lak',
  'Dac Nong',
  'Dien Bien',
  'Dong Nai',
  'Dong Thap',
  'Gia Lai',
  'Ha Giang',
  'Hai Duong',
  'Ha Nam',
  'Ha Tay',
  'Ha Tinh',
  'Hau Giang',
  'Hoa Binh',
  'Hung Yen',
  'Khanh Hoa',
  'Kien Giang',
  'Kon Tum',
  'Lai Chau',
  'Lam Dong',
  'Lang Son',
  'Lao Cai',
  'Long An',
  'Nam Dinh',
  'Nghe An',
  'Ninh Binh',
  'Ninh Thuan',
  'Phu Tho',
  'Phu Yen',
  'Quang Binh',
  'Quang Nam',
  'Quang Ngai',
  'Quang Ninh',
  'Quang Tri',
  'Soc Trang',
  'Son La',
  'Tay Ninh',
  'Thai Binh',
  'Thai Nguyen',
  'Thanh Hoa',
  'Thua Thien-Hue',
  'Tien Giang',
  'Tra Vinh',
  'Tuyen Quang',
  'Vinh Long',
  'Vinh Phuc',
  'Yen Bai',
  'Can Tho',
  'Da Nang',
  'Hai Phong',
  'Hanoi',
  'Ho Chi Minh',
  'Nha Trang',
  'Vung Tau',
  'Phu Quoc',
  'Dat Lat',
  'Hoi An',
  'Vinh Loc',
  'Sapa',
  'Tp.VungTau',
  'Tan Binh',
  'Chau Long',
  'Tan Phu',
  'BaRiaVungTau',
  'Hue',
  'TP.Hue',
  'Tp.Ho Chi Minh',
  'Ba Ria',
  'Da Lat',
];
